version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: wallet
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet_pwd
      POSTGRES_DB: walletdb_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: